{% set name = "google-api-python-client" %}
{% set version = "2.159.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0680e43264f3d6e9d6e95e86aff54a4145762032f90e23c8fe542096a7b4910a
  patches:
    - patches/0001-removed-dev-pinnings.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  build: 
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - httplib2 >=0.19.0,<1.dev0
    - google-auth >=1.32.0,<3.0.0.dev0,!=2.24.0,!=2.25.0
    - google-auth-httplib2 >=0.2.0,<1.0.0
    - google-api-core >=1.31.5,<3.0.0.dev0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - uritemplate >=3.0.1,<5


# raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
# google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
{% set deselect_tests = " --deselect=tests/test_discovery.py::Universe::test_client_options_universe_configured_with_mtls" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_discovery.py::Universe::test_universe_env_var_configured_with_mtls" %}

test:
  source_files:
    - tests
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
    - pytest -v {{ deselect_tests }} tests
  requires:
    - pip
    - pytest
    - parameterized


about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_family: Apache
  license_file: LICENSE
  summary: Google API Client Library for Python
  description: This is the Google API Python client library for Google's discovery based APIs.
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
