{% set name = "google-api-python-client" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b24022c75b38a1b323a74129d09af1131078b7c0d337ac8fa6461d5f8b2b0e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-core >=1.18.0,<2dev
    - google-auth >=1.16.0
    - google-auth-httplib2 >=0.0.3
    - httplib2 >=0.9.2,<1dev
    - six >=1.6.1,<2dev
    - uritemplate >=3.0.0,<4dev

test:
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_file: LICENSE
  summary: Google API Client Library for Python
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
