{% set name = "google-api-python-client" %}
{% set version = "1.6.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "bb1f27740f6596f8272a2e1033d93d68e27e8ed5d22d6ab957e3f1d3f8ce05f6" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - httplib2 >=0.9.2,<1dev
    - oauth2client >=1.5.0,<5.0.0dev
    - six >=1.6.1,<2dev
    - uritemplate >=3.0.0,<4dev

test:
  imports:
    - apiclient
    - googleapiclient
    - googleapiclient.discovery_cache

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache 2.0 and MIT
  summary: 'Google API Client Library for Python'
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
