{% set version = "1.7.5" %}

package:
  name: google-api-python-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/google-api-python-client/google-api-python-client-{{ version }}.tar.gz
  sha256: 85674c2aa4b96a478b4d0859f8b814879551a4eaf6977ead6f94863aa8ab46ef

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - httplib2 >=0.9.2,<1dev    
    - google-auth >=1.4.1
    - six >=1.6.1,<2dev
    - google-auth-httplib2 >=0.0.3
    - uritemplate >=3.0.0,<4dev

test:
  imports:
    - apiclient
    - googleapiclient
    - googleapiclient.discovery_cache

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache 2.0 and MIT
  license_file: LICENSE
  summary: 'Google API Client Library for Python'
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
