travis:
  secure:
    BINSTAR_TOKEN: BPHd0LMboNLsG1xJI/Drp5sPw2BluTNoWEDGSf099n5N9aewR3eDV+IaUMXp/tevPDxrzaUwYkeqAkLAeqgzXUT2d2lB9MVBUPTwrTW4zSj3FA7lpsxQGPyunbXV3qdOzsJFhVI/jvdpmAKW+gIMYJ46p82CdM4d7fk1IIQ/weraWu7oikoNGBQBpmag1K1bsI5NDY6GPwVGRh5QTlmvB2qzc1k7qPyq+2rN23H3Y3ETKh92D+lT2doTnUXHPmr/gglnPyP8HyUcdOyTiu2qp1ONGBciAoPtKn17fdMIn7urH2C6Kp4zAJ2VDLulXuKsb9riAtvo6AoWSxRpLsHAJa0NkazDBFt2+/XewDhbTHgqmz2S7OdRtSCdM2o0ESW1JV3o2zYKldJkI6HFDZMnUEDRemWklpTAVlashz8b/AF/F85h91h5gcHwx+L2XV0BCCO39vk9a2J7cAAjb+BsBsraLigH1Ifl02wuxIx6yhW7abm8ao8nr8Rv5utgdLMOW+EhkuwxhBZ8ZpxFud6Al3DHczv8agK4aAf10QVh8+bfkJR4zP3D/VqN9U1FJx7TcQ00Kevvo6UrCpI1skikIWSmqYhAW7DBF8gKqi3K1g+xG8jEx7M2Iv3bdykF6FBQBXRHwHVW79onOsrHWe6x1QlZCu1IBNm4T7Je6IJHxJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
