travis:
  secure:
    BINSTAR_TOKEN: Kq9GbPYzuWmoxDqwc8HdaOZ1uDLQjZG2cXdhOv5X9GCC6lcoqwmD+I+/Z3rB3PeJpW4Q3TvApJ2Ns3lCdNnMRjk+PSj2Bse6O6NkUKHxO+4hfkCz2NI4sUsfvhhNisyNqL6hUTLpsKJWPwjShj2d3hdrggSdlA/NpRY83XcOFNiwQDJKa7/SKoDphG6R0ewEwWSTKsOuJ4cCETR1XRvij659eSaQ9Rx7wwh/vZ/legvqSNCenePTsDosgN2M1uS01C8OKgohCjT3cbhL+6ekoI7FNQTrIXCOJg+1P9PvadUKQjXCebqRbbNpisRu9QNBpzcDcMpDaiUsgOF/ui8XwL4iBmrvS1K8sd+TmHmMmXgd8O18sJinR3Ci9ktLRHIXgNgDFESmA4+UwibzFYFp9sa4e+qvBxI9sikEZ5uIM+nsI8mA4v84wKkb8z5V9PlDy3J6at6RH0z8P2uLZUKUs5x8yd09wSJjhCGQcc3+s2a1nR+ZJWiDn1EWDUhLCywSfvtDSgwOwxfQ8Y/2/p/DGmGDJW2XjePAXp2K0fDR1LpjqifUoGwUHaZhR1b39FTr80mBfY38//Cr8SQYW2NIgBWbqg/7NZItqwGj4LiwslfPGh1VlFQYh76IY9mH4CSFhIythws7GU8wTKX4mAJBomS2hnNgvv7JK14m3apQQDs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
