travis:
  secure:
    BINSTAR_TOKEN: TtHt0AzikD8u6oAiGf5JRTlLR2A6OzLbb3f9QOjBdP+GAOSuINEJ6mbuMSlUnKebc1rAU81LiuYkNh3smbVxBt/D1QSXhf8u7dWRcKZWSx0HBxdRNMMXev88B3nD4ZWOnDgcy603Mpfk/opnC6swobzXxFh76qTjjKSQqEjrgfwd2w03Vukt89q5XKM1twBO+PLb+XvAgI7+aw74avjIQqESJRr46n9oWjpdyvrTnGuyUtBMPJlokuNXrEyaRzQcWtzzLdYZaeUGOIMORo022MDBN+3VYvSwakSx0z1XVL/RMYc6zrcp1O+86uDFn4/fbFitgUwakEZHQny176RBXvs3+dgamTocppjfLb0QEmsYP5Hfli7hIaTB3SIoTp8z8RZlZlRs4qVZjXm+fNbMF9JY1a1Llrls0Y+HgSKrS370FL2SeUCCi5n7KL25qKfXRNKJJpoO7iS58t71yXF4hPH6145NDtp5uBsFV0NvPdpeiw9iMOFJUi7FkCf2s+1RSZ6oU3ztbOcjh9ymfpIHgkWIZQx4wuTEbyeb9oiFJ/IHlTwelIaAHiIygleX5Qc1w/3DruqOT9xsF5NNuTDDfBu1GsSztmAvRRDefx6T4CDwHyytJ57blaVAiaB3tS9LHTjBAbTWrJdDCVam6/52VClIkMPSHefJ7LPtUGORWy0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
