travis:
  secure:
    BINSTAR_TOKEN: Q9BGRWCr79zCyskRb+Qmf+30sMpBpTclDI145O35lYLu0tfkkie3FTOXUtpRW8YInxa8eHlzA+60cjnai9xN3GhDANXKv31oPkOpsPxoNWWea5muuYlLknYfa/WJEbLiQXBQiwGWGY3CD4rtyz0vyOPVT16P6YJHGC3iG4+RfWfZIwUz1NMaazQMxpkTlz79EbD+wgjJQzZcGcPvzMinXnIE69JGb2/L7Hf6jgVjdouyyF7GlE2DqQrKRs+mb2nZjAWdpNrdI185LUppan52EgaSyLJVwElBv92D8XFEhJIe4Lt8U2sDTTfCu32XWjUKfX6u2OBv+zGUhUypHQuSjW2SBjglgJunGbDN42oMDHOI7L7Dzb6m9DL4M3x/w9rJuQkQA/oFxgbSyII6rhjw/m2+FeWxU0Wlmnje2e0NNAr0pO8MHr9qbjAqDoXVBFkt3OQ0x3qP7NB7aRhbZraLeM+QtuvGieM6kjZ9Hjkw3/xzsAts6dC04ZfgLC2tn+5hfc0RGO704AD6U04VWpTpdXquYApv5wRJ2rJ3au1VgFzbY7YjRRNYS/vaf4K/kVPgsgkbVT2na/Z3Hekv/S5xXJMQgLroW/oZc8aboMsINODN0u9OENNkzSJwUDcbmBfSGFxuuXLsLU5trsGvL5XE7cNQPZPYt1+SYeiIklGaM38=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
